Update update-version.yml

diff --git a/.github/workflows/update-version.yml b/.github/workflows/update-version.yml
--- a/.github/workflows/update-version.yml
+++ b/.github/workflows/update-version.yml
@@ -39,13 +39,25 @@ jobs:
       - name: Create Directory and File
         run: |
           # Create the directory for the version if it doesn't exist
-          mkdir -p Updater/$VERSION
+          if mkdir -p Updater/$VERSION; then
+            echo "Directory created: Minecraft-Modpack-Updater/Updater/$VERSION"
+          else
+            echo "Failed to create directory: Minecraft-Modpack-Updater/Updater/$VERSION"
+            exit 1
+          fi
+          
           # Create the file with the link to the release EXE
-          echo "https://github.com/Bristopher/Minecraft-Modpack-Updater/releases/download/$VERSION/Bristopher_Modpack_Updater_v$VERSION.exe" > Minecraft-Modpack-Updater/Updater/$VERSION/Bristopher_Modpack_Updater.txt
-          echo "Link to EXE created at Minecraft-Modpack-Updater/Updater/$VERSION/Bristopher_Modpack_Updater.txt"
+          FILE_PATH="Minecraft-Modpack-Updater/Updater/$VERSION/Bristopher_Modpack_Updater.txt"
+          if echo "https://github.com/Bristopher/Minecraft-Modpack-Updater/releases/download/$VERSION/Bristopher_Modpack_Updater_v$VERSION.exe" > "$FILE_PATH"; then
+            echo "Link to EXE created at $FILE_PATH"
+          else
+            echo "Failed to create file: $FILE_PATH"
+            exit 1
+          fi
           
           # List the directory to check if the file is created
           ls -R Minecraft-Modpack-Updater
+
 
       - name: Update Application Version Link
         run: |
